[build]
  command = "npm run build"
  functions = "functions"
  publish = "dist"

[dev]
  functions = "functions"
  publish = "dist"
  port = 3000
  targetPort = 5175

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
